# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-20 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='room',
            field=models.CharField(default=1, help_text='Max 160 char.', max_length=160, unique=True),
            preserve_default=False,
        ),
    ]
