# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-20 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_topic_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='room',
        ),
    ]
