# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-20 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_remove_topic_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='room',
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
